DROP TABLE dishes IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE dishes
(
    id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    dish_name        VARCHAR(255)            NOT NULL,
    price            INTEGER                 NOT NULL
);
CREATE UNIQUE INDEX unique_dish_name_price_idx
    ON DISHES (dish_name, price);